# Generated by Django 6.0.2 on 2026-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_post_like',
        ),
        migrations.AddField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'session_key'), name='unique_session_post_like'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
